### ISSUE TITLE
keras cifar example error: `steps_per_epoch=None` is only valid for a generator based on the `keras.utils.Sequence` class.

### ISSUE THREAD

**Issue by junxnone** [junxnone/tio#290]
# Error log:
```
Traceback (most recent call last):
  File "cifar10_resnet.py", line 426, in <module>
    callbacks=callbacks)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training_generator.py", line 55, in fit_generator
    raise ValueError('`steps_per_epoch=None` is only valid for a'
ValueError: `steps_per_epoch=None` is only valid for a generator based on the `keras.utils.Sequence` class. Please specify `steps_per_epoch` or use the `keras.utils.Sequence` class.
```
# Workaround
setup the steps_per_epoch in model.fit_generator() function
```
$ git diff cifar10_cnn.py
diff --git a/examples/cifar10_cnn.py b/examples/cifar10_cnn.py
index 4c3e9e8..5a6e61c 100644
--- a/examples/cifar10_cnn.py
+++ b/examples/cifar10_cnn.py
@@ -113,6 +113,7 @@ else:
     # Fit the model on the batches generated by datagen.flow().
     model.fit_generator(datagen.flow(x_train, y_train,
                                      batch_size=batch_size),
+                        steps_per_epoch=100,
                         epochs=epochs,
                         validation_data=(x_test, y_test),
                         workers=4)
```

**Comment by junxnone** [comment]
#25 #9
